spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  
  # Camunda properties
  camunda:
    bpm:
      admin-user:
        id: admin
        password: admin
        first-name: Admin
        last-name: User
      filter:
        create: All tasks

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:thephyscSuperSecretKey123!@#MustBeAtLeast32CharsLong}
  expiration: 86400000 # 24 hours in milliseconds

# Video Services Configuration
video:
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID:your_twilio_account_sid}
    auth-token: ${TWILIO_AUTH_TOKEN:your_twilio_auth_token}
  jitsi:
    app-id: ${JITSI_APP_ID:your_jitsi_app_id}
    api-key: ${JITSI_API_KEY:your_jitsi_api_key}

# File Storage Configuration
storage:
  type: ${STORAGE_TYPE:s3} # local, s3, or azure - default to local for development
  s3:
    bucket-name: ${S3_BUCKET:the-physc-storage}
    region: ${S3_REGION:eu-north-1}
    access-key: ${S3_ACCESS_KEY:AKIA5ZA3QXE6P74TJ26N}
    secret-key: ${S3_SECRET_KEY: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}
    profile-path: ${S3_PROFILE_PATH:/profiles}
    provider-path: ${S3_PROVIDER_PATH:/provider-docs}
    url: ${S3_URL:https://s3.amazonaws.com/the-physc-storage} # Public URL for the bucket
  azure:
    container-name: ${AZURE_CONTAINER:the-physc-storage}
    connection-string: ${AZURE_CONNECTION_STRING:your_connection_string}

# Local File Storage Configuration
file:
  storage:
    location: ${FILE_STORAGE_LOCATION:uploads}
  base:
    url: ${FILE_BASE_URL:https://the-physc-storage.s3.eu-north-1.amazonaws.com}

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000, https://thephysc.com
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  exposed-headers: Authorization
  allow-credentials: true
