spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:health-service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: false

logging:
  level:
    com.thephysc: INFO
    org.springframework: WARN
    org.hibernate: WARN

server:
  port: ${PORT:8080}
